import Head from "next/head";
import MyAppBar from "@/Components/Common/MyAppBar";
import { ThemeProvider } from "@mui/material";
 
import {theme} from "@/styles/mui/theme";
 
 
 
export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog | The Movie Lovers Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar/>
      <div></div>
    </>
  );
}
 
 